# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://hindi-education.com/"  # Include trailing slash
title = "Online Education in Hindi"
author = "Mragank Shandilya"
copyright = "Copyright © 2021, Hindi-Education.com Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"

disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
